Traceback (most recent call last):
  File "trainings/train.py", line 112, in <module>
    train_processor = Train()
  File "trainings/train.py", line 32, in __init__
    self.vocab = Vocab(args.vocab_path, args.vocab_size)
  File "/Users/vitou/Workspaces/AizawaLab/scientific_question_generation/models/scibert/data_util/data.py", line 35, in __init__
    with open(vocab_file, 'r') as vocab_f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vitou/workspace/projects/scientific_paper_QG/data/seq2seq_data_bin/vocabs.txt'
